name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive

            - name: build
              uses: MitchellThompkins/cocoOS_github_action@v0.0.3
              with:
                command: make build.cmake build.makefile
